Changes: More portable dependencies checks
Signed-off-by: Miroslav Safr <Miroslav.Safr@gmail.com>

diff --git a/docfind b/docfind
--- a/docfind
+++ b/docfind
@@ -23,6 +23,7 @@ usage() {
     echo " -no --name-only .................... print only filenames (def: disabled)"
     echo " "
 }
+die() { echo "ERROR: $*\n" ; exit 1 ; }
 
 START_TIME=`date +'%s'`
 CASE_SENS=0
@@ -45,26 +46,21 @@ while [ $# -gt 0 ]; do
             elif [ -z "$SEARCH_DIR" ]; then
                 SEARCH_DIR=$1
             else
-                echo "There can be only 2 arguments without <WHAT> <WHERE>, exiting.." ; exit 1
+                die "There can be only 2 arguments without <WHAT> <WHERE>, exiting.."
             fi
         ;;
     esac
     shift
 done
 
-if [ -z "$WHAT" ]; then
-    echo "You have to specify searching pattern, exiting.." ; exit 1
-fi
+[ -z "$WHAT" ] && die "You have to specify searching pattern, exiting.."
 
 if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
     SEARCH_DIR="./"
 fi
 
 #check dependencies
-if [ ! -e "/usr/bin/unoconv" ]; then
-    echo "Not installed unoconv, exiting.."
-    exit 1
-fi
+command -v unoconv 1>/dev/null 2>&1 || die "Not installed unoconv, exiting.."
 
 #check if terminal supports colors
 COLORS=
diff --git a/htmlfind b/htmlfind
--- a/htmlfind
+++ b/htmlfind
@@ -22,6 +22,7 @@ usage() {
     echo " -no --name-only .................... print only filenames (def: disabled)"
     echo " "
 }
+die() { echo "ERROR: $*\n" ; exit 1 ; }
 
 START_TIME=`date +'%s'`
 CASE_SENS=0
@@ -44,7 +45,7 @@ while [ $# -gt 0 ]; do
             elif [ -z "$SEARCH_DIR" ]; then
                 SEARCH_DIR=$1
             else
-                echo "There can be only 2 arguments without <WHAT> <WHERE>, exiting.." ;  exit 1
+                die "There can be only 2 arguments without <WHAT> <WHERE>, exiting.."
             fi
         ;;
     esac
@@ -60,11 +61,7 @@ COLORS=
 tput setaf 1>/dev/null 2>&1 && COLORS=" --color=always "
 
 #check dependencies
-if [ ! -e "/usr/bin/html2text" ]
-then
-    echo "Not installed html2text, exiting.."
-    exit 1
-fi
+command -v html2text 1>/dev/null 2>&1 || die "Not installed html2text, exiting.."
 
 #case sensitive flag - by default ignore cases
 CSF="-i "
diff --git a/pdffind b/pdffind
--- a/pdffind
+++ b/pdffind
@@ -22,6 +22,7 @@ usage() {
     echo " -no --name-only .................... print only filenames (def: disabled)"
     echo " "
 }
+die() { echo "ERROR: $*\n" ; exit 1 ; }
 
 START_TIME=`date +'%s'`
 CASE_SENS=0
@@ -56,9 +57,7 @@ if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
 fi
 
 #check dependencies poppler-utils package
-if [ ! -e "/usr/bin/pdftotext" ]; then
-    echo "Not installed xml2, exiting.." ; exit 1
-fi
+command -v pdftotext 1>/dev/null 2>&1 || die "Not installed pdftotext (poppler-utils), exiting.."
 
 #check if terminal supports colors
 COLORS=
diff --git a/pptfind b/pptfind
--- a/pptfind
+++ b/pptfind
@@ -22,6 +22,7 @@ usage() {
     echo " -no --name-only .................... print only filenames (def:disabled)"
     echo " "
 }
+die() { echo "ERROR: $*\n" ; exit 1 ; }
 
 START_TIME=`date +'%s'`
 CASE_SENS=0
@@ -56,9 +57,7 @@ if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
 fi
 
 #check dependencies
-if [ ! -e "/usr/bin/unoconv" ]; then
-    echo "Not installed unoconv, exiting.." ;  exit 1
-fi
+command -v unoconv 1>/dev/null 2>&1 || die "Not installed unoconv, exiting.."
 
 #check if terminal supports colors
 COLORS=
diff --git a/xmlfind b/xmlfind
--- a/xmlfind
+++ b/xmlfind
@@ -23,6 +23,7 @@ usage() {
     echo " -ext --extension  <ext>  ........... choose extension (def: xml)"
     echo " "
 }
+die() { echo "ERROR: $*\n" ; exit 1 ; }
 
 START_TIME=`date +'%s'`
 CASE_SENS=0
@@ -47,7 +48,7 @@ while [ $# -gt 0 ]; do
             elif [ -z "$SEARCH_DIR" ]; then
                 SEARCH_DIR=$1 ;
             else
-                echo "There can be only 2 arguments without <WHAT> <WHERE>, exiting.." ; exit 1
+                die "There can be only 2 arguments without <WHAT> <WHERE>, exiting.."
             fi
         ;;
         esac
@@ -55,20 +56,14 @@ while [ $# -gt 0 ]; do
 done
 EXT_RE=`printf '\.%s$' $EXT`
 
-if [ -z "$WHAT" ]; then
-    echo "You have to specify searching pattern, exiting.." ; exit 1
-fi
+[ -z "$WHAT" ] && die "You have to specify searching pattern, exiting.."
 
 if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
     SEARCH_DIR="./"
 fi
 
 #check dependencies xml2 package
-if [ ! -e "/usr/bin/xml2" ]
-then
-    echo "Not installed xml2, exiting.."
-    exit 1
-fi
+command -v xml2 1>/dev/null 2>&1 || die "Not installed xml2, exiting.."
 
 #check if terminal supports colors
 COLORS=
