New: gcfind behaves as recursive cat if WHAT argument is missing, Fix: help update
Signed-off-by: Miroslav Safr <Miroslav.Safr@gmail.com>

diff --git a/gcfind b/gcfind
--- a/gcfind
+++ b/gcfind
@@ -4,19 +4,23 @@
 #author: Miroslav Safr <miroslav.safr@gmail.com> 
 VERSION=NA
 VERSION_DATE=NA
+
+#support color escape characters on different terminals
+alias echo="/bin/echo -e"
+
 BASENAME=`basename $0`
 usage() {
     echo "$BASENAME ${VERSION} - extended recursive search for git configs"
-    echo " http://safrm,net/projects/efind/"
-    echo "Usage:$BASENAME [OPTIONS]... PATTERN [SEARCHING_DIR]"
-    echo " PATTERN ............................ string (requires \"\" if contains spaces) "
-    echo " options: "
-    echo " --help ............................. shows command line help"
-    echo " -cs ................................ case sensitive content search (by default it is insensitive)"
+    echo "  http://safrm,net/projects/efind/"
+    echo "Usage:$BASENAME [OPTIONS]... [PATTERN] [SEARCHING_DIR]"
+    echo "  PATTERN ............... string (requires \"\" if contains spaces) "
+    echo "  SEARCHING_DIR ......... root directory for searching (default: current)"
+    echo "Options: "
+    echo "  --help ................ shows command line help"
+    echo "  -cs ................... case sensitive content search (default:insensitive)"
+    echo "Note: it behaves as recursive cat if "WHAT" argument is missing"
     echo " "
 }
-#support color escape characters on different terminals
-alias echo="/bin/echo -e"
 
 START_TIME=`date +'%s'`
 CASE_SENS=0
@@ -25,7 +29,9 @@ FOUND_COUNT=0
 FOUND_COUNT_FN=0
 while [ $# -gt 0 ]; do
   case "$1" in
-    --help) usage exit ;;
+    --help) usage 
+            exit 1
+            ;;
     -cs) CASE_SENS=1 ;;
     * )
         if [ -z "$WHAT" ]; then  
@@ -38,12 +44,7 @@ while [ $# -gt 0 ]; do
         ;;
   esac
   shift
-done
-
-
-if [ -z "$WHAT" ]; then 
-    echo "You have to specify searching pattern, exiting.."; exit 1;
-fi
+done 
 
 if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
 	SEARCH_DIR="./"
